ktor:
  application:
    modules:
      - com.aniable.yggdrasil.ApplicationKt.module
  deployment:
    port: 8080
db:
  url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1"
  driver: "org.h2.Driver"
  user: "root"
  password: ""
