ktor:
  application:
    modules:
      - com.aniable.yggdrasil.ApplicationKt.module
  deployment:
    port: 8080
db:
  url: "jdbc:postgresql://localhost:5432/yggdrasil"
  driver: "org.postgresql.Driver"
  user: "yggdrasil"
  password: "changeme"
jwt:
  # The secret key must be an HMAC-SHA-512 (HS512) digest. See: https://jwt-keys.21no.de/api/generate/HS512?bytes=64
  secret: "QKVuTfNAT5CC3GT9yda5gpwSRTsDTuqDiUUxYl31+aiq9eMNY5IqaES7GwE4nt6jhnl3EKLbEkLFzzItvNLifQ=="
  # The expiration is how long the access token lasts. Can be a value such as: "15m", "1h", "1h 30m", "1d", etc.
  expiration: "1d"
