name: yggdrasil

services:
  postgres:
    image: postgres:17.0-alpine3.20
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=yggdrasil
      - POSTGRES_PASSWORD=changeme
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: unless-stopped
